quarkus.datasource.db-kind=postgresql 

quarkus.datasource.username=postgres
<<<<<<< HEAD

quarkus.datasource.password=Makeover3
#url de conexion a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2_db
=======
quarkus.datasource.password=postgres

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/grupal
>>>>>>> origin2/jdk

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

<<<<<<< HEAD
quarkus.log.category."org.hibernate.SQL".level=DEBUG

quarkus.log.category."org.hibernate.type.descriptor.sql".level=TRACE

=======
quarkus.transaction-manager.default-transaction-timeout=PT240S
#quarkus.hibernate-orm.sql-load-script=no-file
>>>>>>> origin2/jdk
